project:
  type: website
  output-dir: docs

website:
  title: "ipgttanalysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    execute:
      warning: false
      message: false

editor: visual

